server:
  port: 8080
spring:
  datasource:
    url: jdbc:mariadb://db-dpk8a.pub-cdb.ntruss.com/jejupower?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: ojteam_admin
    password: rlaclgns5628!
  jpa:
    hibernate:
      ddl-auto: create